version: " 3.8 "
services:
 client:
   build: ./frontend
   ports:
    -3000:3000 
 backend:
   build:   ./backend
   ports:
    -3001:3001
 db:
   images: mongo 4.0-focal
   ports:
   - 27017:27017
   volumes:
   -yolo: /data/db

  

  
