---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend.yaml
spec:
  selector:
    matchLabels:
      app: yolo
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: backend
        image: "node:14.16.0 -alpine3.13
        env:
        - name: "PORT"
          value: "3001"