---
- name: client side
  hosts: frontend
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "14"
    frontend_image: "keendra01/client:v1"
    frontend_port: "3000"
  tasks:
    - name: Install GPG
      tags: nodejs, install, setup
      apt:
        name: gnupg
        update_cache: yes
        state: present
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Clone YOLO repository
      git:
        repo: https://github.com/Metto01/yolo.git
        dest: /home/sandra/Moringa/yolo/
        clone: yes
        update: yes
    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=present
    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
    - name: Set up frontend container
      include_role:
        name: frontend
      vars:
        frontend_image: "{{ frontend_image }}"
        frontend_port: "{{ frontend_port }}"
#volumes: "{{ volumes }}"
      tags:
        - frontend
    - name: Install dependencies from lockfile
      tags: app, build, deploy
      shell: npm install
      args:
        chdir: /home/sandra/Moringa/yolo/client/
    - name: Start App
      tags: app, build, deploy
      shell: forever --minUptime 5000 --spinSleepTime 20000 start -c "npm start" src
      args:
        chdir: /home/sandra/Moringa/yolo/client/

- name: Backend app
  hosts: backend
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "14"
    backend_image: "keendra01/backend:v1"
    backend_port: "3001"
    #volumes: "- yolovol:/var/lib/docker/volumes/yolovol/_data" 

  tasks:
    - name: Install GPG
      tags: nodejs, install, setup
      apt:
        name: gnupg
        update_cache: yes
        state: present
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    - name: Clone YOLO repository
     git:
        repo: https://github.com/Metto01/yolo.git
        dest: /home/sandra/Moringa/yolo/
        clone: yes
        update: yes
    - name: "Install forever (to run Node.js app)."
      npm: name=forever global=yes state=present
    - name: "Check list of Node.js apps running."
      command: forever list
      register: forever_list
      changed_when: false
    - name: Set up backend container
      include_role:
        name: backend
      vars:
        backend_image: "{{ backend_image }}"
        backend_port: "{{ backend_port }}"
        volumes: "{{ volumes }}"
      tags:
      - backend
    - name: Install dependencies from lockfile
      tags: app, build, deploy
      shell: npm install
      args:
        chdir: /home/sandra/Moringa/yolo/backend/
    - name: Start App
      tags: app, build, deploy
      shell: forever --minUptime 3001 --spinSleepTime 20000 start -c "npm start" server.js
      args:
        chdir: /home/sandra/Moringa/yolo/backend/  
        

